site_name: "AG: JavaScript API Docs"
nav:
  - Docs:
      - Home: index.md
      - "enum":
          - "trigger": enum/trigger.md
      - "element":
          - "player": element/player.md
      - "noname":
          - "get":
              - "index": noname/get/get.md
              - "is": noname/get/is.md
          - "game": 
              - "game": noname/game/game.md
theme:
  name: material
  custom_dir: overrides
  features:
      - search.suggest
      - search.highlight
      - search.share
      - navigation.tabs
      - navigation.instant
      - navigation.top
  icon:
      repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
markdown_extensions:
  - toc:
      permalink: ⚓︎
      toc_depth: 3
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
      url_download: true
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
plugins:
  - search:
      separator: '[\s\-\.\_\·]+'
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/leru1015/Noname-Xingbei-Docs
      name: "AG: JavaScript API Docs"
  version:
    provider: mike
    default: rep
  analytics:
    provider: google
    property: G-ZBKP3LLT96
extra_css:
    - css/custom.css
extra_javascript:
    - https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js
    - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
    - js/tablesort.number.min.js
    - js/customJS.js
    - js/jquery.mark.min.js
copyright: "Copyright &copy; 2025 aabbcczhy"
repo_url: https://github.com/leru1015/Noname-Xingbei-Docs
repo_name: leru1015/Noname-Xingbei-Docs
use_directory_urls: False